// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPg0WtnGHwdbgnCZutim6ZT3Hze_LOrw',
    appId: '1:741077587371:web:56cbae69095badfa37aeee',
    messagingSenderId: '741077587371',
    projectId: 'task-manager-d8868',
    authDomain: 'task-manager-d8868.firebaseapp.com',
    storageBucket: 'task-manager-d8868.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQloKgUJBPk2BYRQ01zbEhcmtiYSdSKA',
    appId: '1:741077587371:android:cdc0bebde47bf21b37aeee',
    messagingSenderId: '741077587371',
    projectId: 'task-manager-d8868',
    storageBucket: 'task-manager-d8868.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyPg0WtnGHwdbgnCZutim6ZT3Hze_LOrw',
    appId: '1:741077587371:web:2b83b9313d63828b37aeee',
    messagingSenderId: '741077587371',
    projectId: 'task-manager-d8868',
    authDomain: 'task-manager-d8868.firebaseapp.com',
    storageBucket: 'task-manager-d8868.appspot.com',
  );
}
